### ISSUE TITLE
Mistake in setup

### ISSUE THREAD

**Issue by VincentWallet** [Bouni/flask-hdmi-cec#1]
Hi
Just one comment to inform  that there is a mistake in the setup line : 
sudo cp flask-hdmi-cec.service /etc/systemd/stystem 

Must be sudo cp flask-hdmi-cec.service /etc/systemd/**system.**

Regards.

**Comment by Bouni** [comment]
@VincentWallet 
Thanks for pointing that one out!
Is the system working for you? I'm just curious because so far I'm not aware of other users

**Comment by VincentWallet** [comment]
Yesss it Works ! :)
Thanks for this job and share
I have Also the delay to receive the response from the server but i can deal with that too.
This web service is controlled by my home automation system and homekit now.

**Comment by Bouni** [comment]
Nice 😄 
I work on an advanced version that uses a background task that continuosly polls the state of the device and takes on/off commands an run them in the background. That way I hope to end up with an system that is almost latency free (the returned state is then possibley some seconds old but that isn't relevant to me)
